<?php
/*$api_list[count($api_list)]=array('name'=>'推兔互粉','corn'=>'wtt','url'=>'http://tuitu.sinaapp.com/weibo/','table'=>'tuitu_sinaapp_comweibo','api'=>'tt_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'推兔互听','corn'=>'qtt','url'=>'http://qqtuitu.sinaapp.com/weibo/','table'=>'qqtuitu_sinaapp_comweibo','api'=>'tt_api.php','type'=>'q');
$api_list[count($api_list)]=array('name'=>'推米互粉','corn'=>'tmi','url'=>'http://tuimi.sinaapp.com/','table'=>'tuimi_sinaapp_com','api'=>'tmi_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'转起互粉','corn'=>'zqt','url'=>'http://zhuanqi.sinaapp.com/','table'=>'zhuanqi_sinaapp_com','api'=>'tmi_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'优推互粉','corn'=>'ytt','url'=>'http://ytt.youtuitui.com/','table'=>'ytt_youtuitui_com','api'=>'tmi_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'加加互粉','corn'=>'jjz','url'=>'http://qiuzf.sinaapp.com/','table'=>'qiuzf_sinaapp_com','api'=>'tmi_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'易加互听','corn'=>'wyj','url'=>'http://app801178271.t.tqapp.cn/','table'=>'app801178271_t_tqapp_cn','api'=>'yj_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'互听赏金榜','corn'=>'hsj','url'=>'http://qqsj.sinaapp.com/reward_website/','table'=>'qqsj_sinaapp_comreward_website','api'=>'dr_api.php','type'=>'q');
$api_list[count($api_list)]=array('name'=>'互粉赏金榜','corn'=>'fsj','url'=>'http://www.weibo01.com/reward_website/','table'=>'www_weibo01_comreward_website','api'=>'dr_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'互推达人','corn'=>'wdr','url'=>'http://hutuidaren.sinaapp.com/reward_website/','table'=>'hutuidaren_sinaapp_comreward_website','api'=>'dr_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'推米互听','corn'=>'tmq','url'=>'http://xtuimi.sinaapp.com/','table'=>'xtuimi_sinaapp_com','api'=>'tmi_api.php','type'=>'q');
$api_list[count($api_list)]=array('name'=>'福利社','corn'=>'fls','url'=>'http://fls.manhuajun.com/','table'=>'fls_manhuajun_com','api'=>'fl_api.php','type'=>'q');*/
$api_list[count($api_list)]=array('name'=>'推兔互粉','corn'=>'wtt','url'=>'http://tuitu.sinaapp.com/weibo/','table'=>'tuitu_sinaapp_comweibo','api'=>'tt_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'推米互粉','corn'=>'tmi','url'=>'http://tuimi.sinaapp.com/','table'=>'tuimi_sinaapp_com','api'=>'tmi_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'微同步','corn'=>'wtb','url'=>'http://www.xuanker.com/','table'=>'www_xuanker_com','api'=>'tb_api.php','type'=>'w');
$api_list[count($api_list)]=array('name'=>'推兔互听','corn'=>'qtt','url'=>'http://qqtuitu.sinaapp.com/weibo/','table'=>'qqtuitu_sinaapp_comweibo','api'=>'tt_api.php','type'=>'q');$api_list[count($api_list)]=array('name'=>'易加互听','corn'=>'wyj','url'=>'http://app801178271.t.tqapp.cn/','table'=>'app801178271_t_tqapp_cn','api'=>'yj_api.php','type'=>'q');
$api_list[count($api_list)]=array('name'=>'福利社','corn'=>'fls','url'=>'http://115.29.187.16/','table'=>'115_29_187_16','api'=>'fl_api.php','type'=>'q');
?>