<?
$ai[count($ai)]='火速留名！！！';
$ai[count($ai)]='微博不错！！！';
$ai[count($ai)]='前来围观！！！';
$ai[count($ai)]='值得深思！！！';
$ai[count($ai)]='这真的吗？？？';
$ai[count($ai)]='支持一下！！！';
$ai[count($ai)]='嘻嘻哈哈！！！';
$ai[count($ai)]='天气真好？？？';
$ai[count($ai)]='帮忙转发！！！';
$ai[count($ai)]='恩恩啊啊！！！';
$ai[count($ai)]='又学习了！！！';
$ai[count($ai)]='楼猪你好！！！';
$ai[count($ai)]='路过路过！！！';
$ai[count($ai)]='恩恩啊啊！！！';
$ai[count($ai)]='笑而不语！！！';
$ai[count($ai)]='保持队形！！！';
$ai[count($ai)]='刚掉节操？？？';
$ai[count($ai)]='不知怎么？？？';
$ai[count($ai)]='好好的呢！！！';
$ai[count($ai)]='欣赏楼主！！！';
?>